import React,{useContext,useEffect,useLayoutEffect,useRef,useState} from 'react';
import {X,Plus,MagnifyingGlass,Sparkle,ArrowUpRight,FileText,Check,LinkSimple,ArrowLeft,CaretLeft,CaretRight,ArrowSquareOut,ClockCounterClockwise,Target,CheckCircle} from 'phosphor-react';
import {entities,Report,kindLabel,dateLabel,manager} from './model';
import {useStore,RelatedContext} from './store';
import {canView} from './sharing';
import {NoAccess} from './Share';
import {RelationPicker,codeOf,nameOf} from './RelationPicker';
/** Bàn phím cho phần tử role="button" không phải <button>: Enter và Space đều kích hoạt (không lan lên dòng cha). */
export const onActivate=(fn:()=>void)=>(e:React.KeyboardEvent)=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();e.stopPropagation();fn()}};
/** Textarea tự cao theo nội dung: viết như văn bản, không có thanh cuộn trong ô hay tay kéo. `rows` là chiều cao tối thiểu. */
export function AutoTextarea(props:React.TextareaHTMLAttributes<HTMLTextAreaElement>){
 const ref=useRef<HTMLTextAreaElement>(null);
 const fit=()=>{const el=ref.current;if(!el)return;el.style.height='auto';el.style.height=el.scrollHeight+'px'};
 useLayoutEffect(fit,[props.value]);useEffect(()=>{window.addEventListener('resize',fit);return()=>window.removeEventListener('resize',fit)},[]);
 return <textarea ref={ref} {...props}/>;
}
/** Trạng thái lưu trên bar editor: chấm vàng 'Chưa lưu' khi có thay đổi, dấu ✓ 'Đã lưu · hh:mm' sau khi lưu. */
export function SaveState({dirty,savedAt}:{dirty:boolean;savedAt?:string}){if(!dirty&&!savedAt)return null;return <span className={'save-state '+(dirty?'dirty':'saved')} role="status">{dirty?<><i className="save-dot"/>Chưa lưu</>:<><CheckCircle weight="fill"/>Đã lưu · {savedAt}</>}</span>}
/** Giờ:phút hiện tại cho SaveState. */
export const nowTime=()=>new Date().toLocaleTimeString('vi-VN',{hour:'2-digit',minute:'2-digit'});
export function Button({children,primary=false,quiet=false,...props}:React.ButtonHTMLAttributes<HTMLButtonElement>&{primary?:boolean;quiet?:boolean}){return <button type="button" {...props} className={`button ${primary?'primary':''} ${quiet?'quiet':''} ${props.className||''}`}>{children}</button>}
export function Modal({title,subtitle,children,close,wide=false,drawer=false,footer}:{title:string;subtitle?:string;children:React.ReactNode;close:()=>void;wide?:boolean;drawer?:boolean;footer?:React.ReactNode}){const ref=useRef<HTMLDivElement>(null);useEffect(()=>{const previous=document.activeElement as HTMLElement;ref.current?.focus();const handle=(e:KeyboardEvent)=>{if(e.key==='Escape')close();if(e.key==='Tab'){const els=ref.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input,select,textarea,a[href],[tabindex="0"]');if(!els?.length)return;const first=els[0],last=els[els.length-1];if(e.shiftKey&&(document.activeElement===first||document.activeElement===ref.current)){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}};document.addEventListener('keydown',handle);const overflow=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.removeEventListener('keydown',handle);document.body.style.overflow=overflow;previous?.focus()}},[]);return <div className={`overlay ${drawer?'drawer-overlay':''}`} onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><div className={`dialog ${wide?'wide':''} ${drawer?'drawer':''}`} role="dialog" aria-modal="true" aria-label={title} tabIndex={-1} ref={ref}><header><div><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div><Button quiet aria-label="Đóng" onClick={close}><X size={20}/></Button></header><div className="dialog-body">{children}</div>{footer&&<footer className="dialog-footer">{footer}</footer>}</div></div>}
export function Empty({title,text,children}:{title:string;text:string;children?:React.ReactNode}){return <div className="empty"><FileText size={32}/><h3>{title}</h3><p>{text}</p>{children}</div>}
export function Badge({children,tone='neutral'}:{children:React.ReactNode;tone?:string}){return <span className={`badge ${tone}`}>{children}</span>}
/**
 * Liên kết chỉ đọc. Mặc định: chip mã + tên ngắn (tối đa `max`, còn lại "+n").
 * `compact`: chỉ mã/tên rất ngắn, dạng chữ nối bằng "·" — dùng cho dòng danh sách để không thành bức tường chip.
 * `hide` bỏ liên kết trùng ngữ cảnh (vd. dự án đang mở). Có RelatedContext thì bấm được để mở Lịch sử mục tiêu.
 */
export function Relations({ids,max=3,hide=[],compact=false}:{ids:string[];max?:number;hide?:string[];compact?:boolean}){
 const openRelated=useContext(RelatedContext);const [all,setAll]=useState(false);
 const list=ids.filter(id=>!hide.includes(id)).map(id=>entities.find(e=>e.id===id)).filter((e):e is NonNullable<typeof e>=>!!e);
 if(!list.length)return null;
 const shown=all?list:list.slice(0,max);const rest=list.length-shown.length;
 const tag=(e:typeof list[number])=>['KR','KS'].includes(e.type)?codeOf(e):['Project','Milestone'].includes(e.type)?nameOf(e).split(' · ')[0]:codeOf(e);
 const act=(e:typeof list[number])=>openRelated?{role:'button' as const,tabIndex:0,'aria-label':'Lịch sử '+e.label,onClick:(ev:React.MouseEvent)=>{ev.stopPropagation();openRelated(e.id)},onKeyDown:onActivate(()=>openRelated(e.id))}:{};
 if(compact)return <span className="rel-inline">{shown.map((e,i)=><React.Fragment key={e.id}>{i>0&&<i>·</i>}<span className={openRelated?'link':''} title={e.label} {...act(e)}>{tag(e)}</span></React.Fragment>)}{rest>0&&<><i>·</i><span className="link" role="button" tabIndex={0} aria-label={`Xem thêm ${rest} liên kết`} onClick={ev=>{ev.stopPropagation();setAll(true)}} onKeyDown={onActivate(()=>setAll(true))}>+{rest}</span></>}</span>;
 return <div className="rp-chips readonly">{shown.map(e=><span className={'rp-chip'+(openRelated?' link':'')} key={e.id} title={e.label} {...act(e)}><b>{codeOf(e)}</b><span>{nameOf(e)}</span></span>)}{rest>0&&<button type="button" className="rp-chip more" onClick={()=>setAll(true)}>+{rest}</button>}</div>;
}
/** Giữ tên cũ cho các nơi đang dùng. */
export const EntityRelationPicker=RelationPicker;
export function AIBox({title,children,action}:{title:string;children:React.ReactNode;action?:React.ReactNode}){return <div className="ai-box"><div className="ai-symbol"><Sparkle size={20} weight="fill"/></div><div><strong>{title}</strong><p>{children}</p></div>{action&&<div className="ai-action">{action}</div>}</div>}
/** Nút "nguồn" dưới một đoạn nội dung: nhãn là tiêu đề bản ghi gốc (rút gọn). */
export function SourceButton({ids,open}:{ids:string[];open:(id:string)=>void}){const {data}=useStore();if(!ids.length)return null;return <div className="source-links">{ids.map(id=>{const t=data.reports.find(r=>r.id===id)?.title??data.contributions.find(c=>c.id===id)?.title??'Nguồn';return <button key={id} onClick={()=>open(id)} title={t}><LinkSimple size={13}/> {t.length>40?t.slice(0,38)+'…':t}<ArrowUpRight size={12}/></button>})}</div>}
export function ReportBody({report,open}:{report:Report;open?:(id:string)=>void}){return <><div className="report-metadata"><Badge tone={report.status==='PUBLISHED'?'success':'neutral'}>{report.status==='PUBLISHED'?'Đã gửi':'Bản nháp'}</Badge><span>{kindLabel[report.kind]} · {dateLabel(report.date)} · {report.owner}</span></div>{report.sections.map((s,i)=><section className="reading-section" key={i}>{s.label&&<h3>{s.label}</h3>}<p className="preserve">{s.text||"—"}</p>{open&&<SourceButton ids={s.sources} open={open}/>}</section>)}{!!report.checkins?.length&&<section className="reading-section"><h3>Cập nhật tiến độ KS</h3><table><thead><tr><th>KS</th><th>Tiến độ</th><th>Kết quả đã làm</th><th>Bước tiếp theo</th></tr></thead><tbody>{report.checkins.map(c=><tr key={c.ksId}><td>{entities.find(e=>e.id===c.ksId)?.label}</td><td>{c.progress}%</td><td className="preserve">{c.result}</td><td className="preserve">{c.next}</td></tr>)}</tbody></table></section>}{report.actions.length>0&&<section className="reading-section"><h3>Việc cần làm</h3><table><thead><tr><th>Việc</th><th>Người phụ trách</th><th>Hạn hoàn thành</th></tr></thead><tbody>{report.actions.map((a,i)=><tr key={i}><td>{a.task}</td><td>{a.owner}</td><td>{dateLabel(a.deadline)}</td></tr>)}</tbody></table></section>}<Relations ids={report.relations}/></>}
export function SourceDrawer({id,close,open}:{id:string;close:()=>void;open:(id:string)=>void}){const {data,user}=useStore();const found=data.reports.find(x=>x.id===id);
 // Không có quyền xem báo cáo gốc → chặn cả nội dung lẫn tệp đính kèm.
 if(found&&!canView(data,found,user))return <Modal drawer title="Không có quyền truy cập" close={close}><NoAccess/></Modal>;const r=found;const c=data.contributions.find(x=>x.id===id);return <Modal drawer title={r?.title||c?.title||'Nguồn dữ liệu'} subtitle="Nội dung bản ghi gốc · dữ liệu demo" close={close}>{r?<ReportBody report={r} open={open}/>:c?<><Badge tone={c.confirmationStatus==='CONFIRMED'?'success':'warning'}>Contribution · {c.confirmationStatus==='CONFIRMED'?'Đã xác nhận':c.confirmationStatus==='NEED_MORE_INFO'?'Cần bổ sung':'Chờ xác nhận'}</Badge><h3>Kết quả / ảnh hưởng</h3><p>{c.impact}</p><Relations ids={c.relations}/>{c.evidence.filter(e=>e.type==='Report').map(e=><Button key={e.value} quiet onClick={()=>open(e.value)}><LinkSimple/> {e.label}</Button>)}</>:<Empty title="Không tìm thấy bản ghi" text="Nguồn này không nằm trong dữ liệu demo hiện tại."/>}</Modal>}
/** Cảnh báo khi rời editor còn nội dung chưa lưu. `save` không truyền thì chỉ có Ở lại / Rời không lưu. */
export function LeaveDialog({stay,discard,save,form=false}:{stay:()=>void;discard:()=>void;save?:()=>void;form?:boolean}){return <Modal title={form?"Đóng khi chưa lưu?":"Rời trang khi chưa lưu?"} subtitle={form?"Nội dung vừa nhập chưa được lưu và sẽ mất nếu bạn đóng.":"Nội dung đang soạn chưa được lưu và sẽ mất nếu bạn rời đi."} close={stay}><div className="form-actions"><Button onClick={stay}>{form?"Tiếp tục soạn":"Ở lại"}</Button><Button onClick={discard}>{form?"Đóng không lưu":"Rời không lưu"}</Button>{save&&<Button primary onClick={save}><Check/> {form?"Lưu nháp":"Lưu nháp & rời"}</Button>}</div></Modal>}
/** Khung editor full-page giống iGoal thật: bar trên (Quay lại · actions), nội dung document, panel phải "Báo cáo cũ" và rail icon bên phải. */
/** Một panel bên phải editor, chọn qua icon trên rail. */
export type EditorPanel={key:string;label:string;icon:React.ReactNode;render:()=>React.ReactNode};
/** `aside` = một panel "Báo cáo cũ" mặc định. `panels` = nhiều panel; `panel`/`onPanel` để component cha điều khiển panel đang mở. */
export function EditorFrame({back,backLabel='Quay lại',actions,aside,panels,panel,onPanel,onSave,children}:{back:()=>void;backLabel?:string;actions?:React.ReactNode;aside?:React.ReactNode;panels?:EditorPanel[];panel?:string|null;onPanel?:(k:string|null)=>void;onSave?:()=>void;children:React.ReactNode}){
 // Ctrl S / ⌘S = Lưu nháp (khi màn có lưu nháp). Bar có bóng khi nội dung cuộn xuống dưới nó.
 const saveRef=useRef(onSave);saveRef.current=onSave;const [scrolled,setScrolled]=useState(false);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'&&saveRef.current){e.preventDefault();saveRef.current()}};const sc=()=>setScrolled(window.scrollY>4);document.addEventListener('keydown',key);window.addEventListener('scroll',sc,{passive:true});return()=>{document.removeEventListener('keydown',key);window.removeEventListener('scroll',sc)}},[]);
 const list:EditorPanel[]=panels??(aside?[{key:'aside',label:'Báo cáo cũ',icon:<ClockCounterClockwise/>,render:()=>aside}]:[]);
 const [inner,setInner]=useState<string|null>(list[0]?.key??null);
 const active=panel!==undefined?panel:inner;const set=onPanel??setInner;const cur=list.find(p=>p.key===active);
 return <div className={'editor-frame '+(cur?'with-aside':'')}><header className={"editor-bar"+(scrolled?" scrolled":"")}><Button quiet onClick={back}><ArrowLeft/> {backLabel}</Button><div className="head-actions">{actions}</div></header><main className="editor-main"><div className="editor-doc">{children}</div></main>{cur&&<aside className="editor-aside" key={cur.key}>{cur.render()}</aside>}{list.length>0&&<div className="editor-rail">{list.map(p=><button key={p.key} aria-label={p.label} title={p.label} className={active===p.key?'active':''} onClick={()=>set(active===p.key?null:p.key)}>{p.icon}</button>)}</div>}</div>;
}
/** Panel "Báo cáo cũ" bên phải editor: phân trang từng báo cáo, là chính các nguồn AI được dùng. */
export function OldReportsPanel({ids,open,close,title='Báo cáo cũ',hint}:{ids:string[];open:(id:string)=>void;close?:()=>void;title?:string;hint?:string}){
 const {data}=useStore();const list=ids.map(id=>data.reports.find(r=>r.id===id)).filter((r):r is Report=>!!r).sort((a,b)=>b.date.localeCompare(a.date));const [i,setI]=useState(0);const r=list[Math.min(i,list.length-1)];
 return <div className="old-reports"><div className="old-reports-head"><h3>{title}</h3>{close&&<Button quiet aria-label="Đóng" onClick={close}><X size={18}/></Button>}</div>{hint&&<p className="hint">{hint}</p>}{list.length?<><div className="pager"><span>{Math.min(i,list.length-1)+1}/{list.length}</span><span><Button quiet aria-label="Trước" disabled={i<=0} onClick={()=>setI(i-1)}><CaretLeft/></Button><Button quiet aria-label="Sau" disabled={i>=list.length-1} onClick={()=>setI(i+1)}><CaretRight/></Button></span></div><article className="old-report-card"><div className="old-report-owner"><span className="avatar tiny">{r.owner.trim().split(/\s+/).pop()?.[0]}</span><div><strong>{r.owner}</strong><small>{dateLabel(r.date)}</small></div><Button quiet aria-label="Mở bản đầy đủ" onClick={()=>open(r.id)}><ArrowSquareOut size={16}/></Button></div><h4>{r.title}</h4>{r.sections.map((s,j)=><section key={j}>{s.label&&<strong>{s.label}</strong>}<p className="preserve">{s.text||'—'}</p></section>)}</article></>:<p className="hint">Chưa có báo cáo cũ.</p>}</div>;
}
/** Chip người dùng kiểu iGoal (avatar + tên + x), dùng cho "Quản lý trực tiếp". */
export function UserChip({name=manager.name,removable=true}:{name?:string;removable?:boolean}){return <span className="user-chip"><span className="avatar tiny">{name.trim().split(/\s+/).pop()?.[0]}</span>{name}{removable&&<X size={12}/>}</span>}
/** Hàng meta trong editor: nhãn trái, giá trị phải. */
export function MetaRow({label,children}:{label:string;children:React.ReactNode}){return <div className="meta-row"><span>{label}</span><div>{children}</div></div>}
/** Thanh tiến độ kiểu iGoal: vàng khi có tiến độ, xám khi 0%. */
export function ProgressBar({value}:{value:number}){return <div className="progress"><div className="progress-track"><span style={{width:`${Math.min(100,Math.max(0,value))}%`}}/></div><strong>{value}%</strong></div>}
export function PageHead({eyebrow,title,description,children}:{eyebrow?:string;title:string;description?:string;children?:React.ReactNode}){return <div className="page-head"><div>{eyebrow&&<div className="eyebrow">{eyebrow}</div>}<h1>{title}</h1>{description&&<p>{description}</p>}</div><div className="head-actions">{children}</div></div>}
